import type { Language, WorkerSkill } from "./shramsetu-logic";

export const copy = {
  Hindi: {
    active: "हिं",
    addedJobs: "naye jobs feed mein hain",
    addEntry: "+ Add karein",
    addJob: "Naya job jodein",
    addJobSubtitle: "Kaam ki details bhar kar job feed update karein.",
    all: "All",
    applied: "applied",
    apply: "Abhi apply karein",
    back: "Back",
    bestMatch: "Aapka best job match",
    byContinuing: "By continuing, you agree to ShramSetu's terms and privacy.",
    chartTitle: "Kamaai aur kharch trend",
    chartWeek: "Week",
    chartMonth: "Month",
    company: "Company / Contractor",
    companyPlaceholder: "Jaise, Sunrise Builders",
    continue: "Aage Badhein",
    days: "din",
    demo: "Demo",
    digitalId: "SHRAMSETU DIGITAL ID",
    digitalIdentity: "DIGITAL IDENTITY",
    earnings: "Kamaai",
    earningsLabel: "Aaj ki kamaai",
    earningsSaved: "Kamaai entry save ho gayi",
    english: "EN",
    experience: "Experience",
    experienceHint: "Zyada tajurba, behtar daily range",
    fair: "Fair Wage",
    fairAdvice: "AI Estimate hai | Professional advice ke liye kisi expert se milein.",
    fairEstimate: "AI ESTIMATE",
    fairInRange: "Offer ₹950 hota to yeh fair range mein hota.",
    fairOutOfRange: "₹950 offer aapke current fair range se alag hai.",
    findJobs: "Kaam dhoondhein",
    hindi: "हिं",
    home: "Home",
    jobs: "Kaam",
    jobsFound: "verified jobs",
    jobsLabel: "Sabhi kaam dekhein",
    jobsRequired: "Company, role, location, wage aur duration bhar dein",
    language: "Language / भाषा",
    languageHint: "App language badlein",
    languageToast: "Hindi mode selected",
    location: "Location",
    locationPlaceholder: "Jaise, Lucknow • 3 km",
    logout: "Logout",
    logoutConfirm: "Kya aap logout karna chahte hain?",
    logoutTitle: "Logout",
    monthlySavings: "Is mahine ki bachat",
    name: "Namaste, Ramesh",
    newEarning: "Nayi kamaai entry",
    newExpense: "Naya kharch",
    newJobSaved: "Naya job feed mein add ho gaya",
    noJobs: "Koi kaam nahi mila",
    noJobsHint: "Search ya filter badal kar dekhein.",
    otp: "OTP daalein",
    otpHint: "OTP nahi mila? 00:28 mein resend",
    otpInvalid: "Demo OTP 1234 use karein",
    otpSent: "par bheja gaya",
    payment: "Baaki payment: ₹950",
    pendingPayment: "ABC Construction • 3 din pehle",
    perDay: "din",
    phoneHint: "Aapke number par secure OTP bhejenge",
    phoneInvalid: "10 digit mobile number daalein",
    phoneTitle: "Apna mobile number daalein",
    profile: "Profile",
    profileSettings: "Profile settings",
    recentEarnings: "Recent income",
    recentExpenses: "Recent spend",
    role: "Job role",
    rolePlaceholder: "Jaise, Senior Mason Required",
    salary: "Daily wage",
    saveEntry: "Save entry",
    saveJob: "Job feed mein add karein",
    savings: "Bachat",
    savingsPlan: "Savings plan",
    score: "Trust Score",
    searchJobs: "Skill search karein",
    selectSkill: "Aapki skill",
    spend: "Kharch",
    spendLabel: "Aaj ka kharch",
    spendSaved: "Kharch entry save ho gayi",
    todaySavings: "Aaj ki bachat",
    total: "Total",
    trend: "Income ₹950 • Spend ₹350",
    verified: "Aapki pehchaan verified hai",
    verifiedIdentity: "Verified identity",
    verifiedSkills: "Verified skills",
    verify: "Verify karein",
    wageDescription: "Apni mehnat ki sahi keemat jaanein.",
    workDuration: "Duration",
    yourMoney: "Aapka paisa, aapke haath mein",
  },
  English: {
    active: "EN",
    addedJobs: "new jobs in your feed",
    addEntry: "+ Add entry",
    addJob: "Add a job",
    addJobSubtitle: "Enter the work details to update the jobs feed.",
    all: "All",
    applied: "applied",
    apply: "Apply now",
    back: "Back",
    bestMatch: "Your best job match",
    byContinuing: "By continuing, you agree to ShramSetu's terms and privacy.",
    chartTitle: "Earnings and expenses trend",
    chartWeek: "Week",
    chartMonth: "Month",
    company: "Company / contractor",
    companyPlaceholder: "For example, Sunrise Builders",
    continue: "Continue",
    days: "days",
    demo: "Demo",
    digitalId: "SHRAMSETU DIGITAL ID",
    digitalIdentity: "DIGITAL IDENTITY",
    earnings: "Earnings",
    earningsLabel: "Today's earnings",
    earningsSaved: "Earnings entry saved",
    english: "EN",
    experience: "Experience",
    experienceHint: "More experience supports a stronger range",
    fair: "Fair Wage",
    fairAdvice: "This is an AI estimate. Consult an expert for professional advice.",
    fairEstimate: "AI ESTIMATE",
    fairInRange: "An offer of ₹950 would fall inside your fair range.",
    fairOutOfRange: "An offer of ₹950 falls outside your current fair range.",
    findJobs: "Find work",
    hindi: "हिं",
    home: "Home",
    jobs: "Jobs",
    jobsFound: "verified jobs",
    jobsLabel: "See all jobs",
    jobsRequired: "Enter a company, role, location, wage, and duration",
    language: "Language",
    languageHint: "Change the app language",
    languageToast: "English mode selected",
    location: "Location",
    locationPlaceholder: "For example, Lucknow • 3 km",
    logout: "Log out",
    logoutConfirm: "Do you want to log out?",
    logoutTitle: "Log out",
    monthlySavings: "Savings this month",
    name: "Hello, Ramesh",
    newEarning: "New earnings entry",
    newExpense: "New expense",
    newJobSaved: "Your new job was added to the feed",
    noJobs: "No jobs found",
    noJobsHint: "Try another search or filter.",
    otp: "Enter OTP",
    otpHint: "Didn't receive it? Resend in 00:28",
    otpInvalid: "Use the demo OTP 1234",
    otpSent: "was sent to",
    payment: "Pending payment: ₹950",
    pendingPayment: "ABC Construction • 3 days ago",
    perDay: "day",
    phoneHint: "We will send a secure OTP to your number",
    phoneInvalid: "Enter a 10-digit mobile number",
    phoneTitle: "Enter your mobile number",
    profile: "Profile",
    profileSettings: "Profile settings",
    recentEarnings: "Recent earnings",
    recentExpenses: "Recent expenses",
    role: "Job role",
    rolePlaceholder: "For example, Senior Mason Required",
    salary: "Daily wage",
    saveEntry: "Save entry",
    saveJob: "Add to jobs feed",
    savings: "Savings",
    savingsPlan: "Savings plan",
    score: "Trust score",
    searchJobs: "Search skills or roles",
    selectSkill: "Your skill",
    spend: "Expenses",
    spendLabel: "Today's expenses",
    spendSaved: "Expense entry saved",
    todaySavings: "Today's savings",
    total: "Total",
    trend: "Income ₹950 • Spend ₹350",
    verified: "Your identity is verified",
    verifiedIdentity: "Verified identity",
    verifiedSkills: "Verified skills",
    verify: "Verify",
    wageDescription: "Know the right value of your work.",
    workDuration: "Duration",
    yourMoney: "Your money, in your hands",
  },
} as const;

export type AppCopy = { [Key in keyof typeof copy.Hindi]: string };

export const skillLabels: Record<Language, Record<WorkerSkill, string>> = {
  Hindi: { Mason: "Mason", Painter: "Painter", Electrician: "Electrician" },
  English: { Mason: "Mason", Painter: "Painter", Electrician: "Electrician" },
};
